export const stages = [
  {
    id: "testimony",
    number: 1,
    title: "Witness",
    subtitle: "証言",
    icon: "👁",
  },
  {
    id: "clarification",
    number: 2,
    title: "Visual Clarification",
    subtitle: "対話",
    icon: "💬",
  },
  {
    id: "visual-extraction",
    number: 3,
    title: "Visual Extraction",
    subtitle: "抽出",
    icon: "📐",
  },
  {
    id: "image-prompt",
    number: 4,
    title: "Image Prompt",
    subtitle: "翻訳",
    icon: "✍️",
  },
  {
    id: "image-generation",
    number: 5,
    title: "Light Emergence",
    subtitle: "光の顕現",
    icon: "🕯",
    center: true,
  },
  {
    id: "fidelity-check",
    number: 6,
    title: "Visual Fidelity",
    subtitle: "忠実性",
    icon: "🔍",
  },
  {
    id: "witness-reflection",
    number: 7,
    title: "Witness Reflection",
    subtitle: "再観察",
    icon: "🪞",
  },
  {
    id: "memory-emergence",
    number: 8,
    title: "Memory Emergence",
    subtitle: "記憶創発",
    icon: "🌱",
  },
  {
    id: "recognition",
    number: 9,
    title: "Recognition",
    subtitle: "認識",
    icon: "✨",
  },
] as const;
